### ISSUE TITLE
Separate section for tech conferences

### ISSUE THREAD

**Issue by rehrumesh** [matteofigus/awesome-speaking#19]
Currently there is a section for CFP web sites. We can add a separate section for conferences where we can maintain a table or a list of links to popular conferences. People who will visit this repo will be able to directly jump into conferences rather than jumping to a CFP sites. 

Pros: 
 * Gain more traction to the repository with conferences list.
 * There are no awesome list which covers conferences with CFP deadlines(Or I couldn't find anything yet. There is a one list but it is a list maintain by the author for personal usage. Hence conference suggestions will not be accepted to the repo unless the author has plan to attend the conf)

Cons:
  * May not be the main objective of this repo. (Please confirm)
  * List may become longer than we expect in the future. (Suggestion is to keep only 1-2 years past conferences)

**Comment by matteofigus** [comment]
Hi @rehrumesh I think this is a good idea. I am not sure this is the main objective of the repo, as you suggested, but why not giving a try? If it doesn't work well, we can always split it to its own list in the future.

👍

**Comment by mmatloka** [comment]
Hello,
We have already a such list, althougth it is not called `awesome` :) https://github.com/softwaremill/it-cfp-list .
I have added a PR to add its link to this repo https://github.com/matteofigus/awesome-speaking/pull/30
